function [ blockNum, blockHistory ] = simulateBlockProb(systemParameters, ...
    TopologyStruct, SimulationParameters, DemandStructTemplate, ...
    SetOfDemandsOnLink, SetOfDemandsOnNode, demandPaths, demandPathLinks)
% simulate noise per link with Monte Carlo

NMonteCarlo = SimulationParameters.NMonteCarlo;

DemandStruct = modifyDemandStruct(DemandStructTemplate);
[blockNum, blockHistory] = simulateOneByOneBlockProb(systemParameters, ...
    TopologyStruct, DemandStruct, NMonteCarlo, ...
    SetOfDemandsOnLink, SetOfDemandsOnNode, demandPaths, demandPathLinks);
